export const customers = [
	{
		name: "Adani Group",
		domain: "adani.com",
		logo: "https://logo.clearbit.com/adani.com",
		score: 794,
		grade: "B",
		trend: 17,
		trendUp: true,
		lastAssessed: "Not assessed",
		reassessment: "-",
		labels: [],
	},
	{
		name: "Birlasoft",
		domain: "birlasoft.com",
		logo: "https://logo.clearbit.com/birlasoft.com",
		score: 861,
		grade: "A",
		trend: 4,
		trendUp: true,
		lastAssessed: "Not assessed",
		reassessment: "-",
		labels: [],
	},
	{
		name: "Google",
		domain: "google.com",
		logo: "https://logo.clearbit.com/google.com",
		score: 672,
		grade: "B",
		trend: 23,
		trendUp: false,
		lastAssessed: "Not assessed",
		reassessment: "-",
		labels: [],
	},
];

export const IPAddresses = [
	{
		source: "DNS",
		ip: "3.6.83.199",
		range: "3.6.0.0 - 3.7.255.255",
		owner: "Amazon Data Services India",
		country: "India",
		score: 794,
		asn: "AS16509",
		asnName: "Amazon Data Services India",
		asnName2: "AMAZON-02",
		asnRegistry: "N/A",
		protocol: "HTTP",
		labels: [],
	},
	{
		source: "DNS",
		ip: "3.7.80.116",
		range: "3.6.0.0 - 3.7.255.255",
		owner: "Amazon Data Services India",
		country: "India",
		score: 794,
		asn: "AS16509",
		asnName: "Amazon Data Services India",
		asnName2: "AMAZON-02",
		asnRegistry: "N/A",
		protocol: "HTTPS",
		labels: [],
	},
	{
		source: "DNS",
		ip: "3.7.109.86",
		range: "3.6.0.0 - 3.7.255.255",
		owner: "Amazon Data Services India",
		country: "India",
		score: 794,
		asn: "AS16509",
		asnName: "Amazon Data Services India",
		asnName2: "AMAZON-02",
		asnRegistry: "N/A",
		protocol: "HTTP",
		labels: [],
	},
	{
		source: "DNS",
		ip: "3.8.12.211",
		range: "3.8.0.0 - 3.8.255.255",
		owner: "Amazon.com",
		country: "USA",
		score: 794,
		asn: "AS14618",
		asnName: "Amazon.com",
		asnName2: "AMAZON-AES",
		asnRegistry: "ARIN",

		protocol: "HTTPS",
		labels: [],
	},
	{
		source: "DNS",
		ip: "3.8.20.15",
		range: "3.8.0.0 - 3.8.255.255",
		owner: "Amazon.com",
		country: "USA",
		asn: "AS14618",
		asnName: "Amazon.com",
		asnName2: "AMAZON-AES",
		asnRegistry: "ARIN",
		protocol: "HTTP",
		labels: ["Internal"],
	},
	{
		source: "DNS",
		ip: "3.22.10.100",
		range: "3.20.0.0 - 3.23.255.255",
		owner: "Amazon.com",
		country: "USA",
		asn: "AS14618",
		asnName: "Amazon.com",
		asnName2: "AMAZON-AES",
		asnRegistry: "ARIN",
		protocol: "HTTPS",
		labels: [],
	},
	{
		source: "DNS",
		ip: "4.2.2.2",
		range: "4.0.0.0 - 4.255.255.255",
		owner: "Level 3 Communications",
		country: "USA",
		asn: "AS3356",
		asnName: "Level 3 Communications",
		asnName2: "LEVEL3",
		asnRegistry: "ARIN",
		protocol: "DNS",
		labels: ["Public DNS"],
	},
	{
		source: "DNS",
		ip: "8.8.8.8",
		range: "8.8.8.0 - 8.8.8.255",
		owner: "Google LLC",
		country: "USA",
		asn: "AS15169",
		asnName: "Google LLC",
		asnName2: "GOOGLE",
		asnRegistry: "ARIN",
		protocol: "DNS",
		labels: ["Public DNS"],
	},
	{
		source: "DNS",
		ip: "8.8.4.4",
		range: "8.8.4.0 - 8.8.4.255",
		owner: "Google LLC",
		country: "USA",
		asn: "AS15169",
		asnName: "Google LLC",
		asnName2: "GOOGLE",
		asnRegistry: "ARIN",
		protocol: "DNS",
		labels: ["Public DNS"],
	},
	{
		source: "DNS",
		ip: "52.95.110.1",
		range: "52.95.110.0 - 52.95.111.255",
		owner: "Amazon.com",
		country: "USA",
		asn: "AS14618",
		asnName: "Amazon.com",
		asnName2: "AMAZON-AES",
		asnRegistry: "ARIN",
		protocol: "HTTPS",
		labels: [],
	},
	{
		source: "DNS",
		ip: "54.239.28.85",
		range: "54.239.16.0 - 54.239.31.255",
		owner: "Amazon.com",
		country: "USA",
		asn: "AS16509",
		asnName: "Amazon.com",
		asnName2: "AMAZON-02",
		asnRegistry: "ARIN",
		protocol: "HTTP",
		labels: [],
	},
	{
		source: "DNS",
		ip: "104.16.132.229",
		range: "104.16.0.0 - 104.31.255.255",
		owner: "Cloudflare, Inc.",
		country: "USA",
		asn: "AS13335",
		asnName: "Cloudflare, Inc.",
		asnName2: "CLOUDFLARENET",
		asnRegistry: "ARIN",
		protocol: "HTTPS",
		labels: ["CDN"],
	},
	{
		source: "DNS",
		ip: "172.67.149.16",
		range: "172.64.0.0 - 172.71.255.255",
		owner: "Cloudflare, Inc.",
		country: "USA",
		asn: "AS13335",
		asnName: "Cloudflare, Inc.",
		asnName2: "CLOUDFLARENET",
		asnRegistry: "ARIN",
		protocol: "HTTPS",
		labels: ["CDN"],
	},
	{
		source: "DNS",
		ip: "1.1.1.1",
		range: "1.1.1.0 - 1.1.1.255",
		owner: "Cloudflare, Inc.",
		country: "Australia",
		asn: "AS13335",
		asnName: "Cloudflare, Inc.",
		asnName2: "CLOUDFLARENET",
		asnRegistry: "APNIC",
		protocol: "DNS",
		labels: ["Public DNS", "CDN"],
	},
	{
		source: "DNS",
		ip: "1.0.0.1",
		range: "1.0.0.0 - 1.0.0.255",
		owner: "Cloudflare, Inc.",
		country: "Australia",
		asn: "AS13335",
		asnName: "Cloudflare, Inc.",
		asnName2: "CLOUDFLARENET",
		asnRegistry: "APNIC",
		protocol: "DNS",
		labels: ["Public DNS", "CDN"],
	},
	{
		source: "Owned Range",
		ip: "103.85.78.1",
		range: "103.85.78.0 - 103.85.79.255",
		owner: "ADANI",
		country: "India",
		score: 884,
		asn: "AS136283",
		protocol: "HTTP",
		labels: ["Owned Range"],
		asnName: "ADANI-AS-IN",
		asnName2: "ADANI-AS-IN",
		asnRegistry: "APNIC",
	},
	{
		source: "Owned Range",
		ip: "103.85.78.2",
		range: "103.85.78.0 - 103.85.79.255",
		owner: "ADANI",
		country: "India",
		score: 903,
		asn: "AS136283",
		protocol: "HTTP",
		labels: ["Owned Range"],
		asnName: "ADANI-AS-IN",
		asnName2: "ADANI-AS-IN",
		asnRegistry: "APNIC",
	},
	{
		source: "Owned Range",
		ip: "103.85.78.3",
		range: "103.85.78.0 - 103.85.79.255",
		owner: "ADANI",
		country: "India",
		score: 884,
		asn: "AS136283",
		protocol: "HTTP",
		labels: ["Owned Range"],
		asnName: "ADANI-AS-IN",
		asnName2: "ADANI-AS-IN",
		asnRegistry: "APNIC",
	},
	{
		source: "Certificate",
		ip: "103.85.78.5",
		range: "103.85.78.0 - 103.85.79.255",
		owner: "ADANI",
		country: "India",
		score: 950,
		asn: "AS136283",
		protocol: "HTTP",
		labels: ["Certificate", "Owned Range"],
		asnName: "ADANI-AS-IN",
		asnName2: "ADANI-AS-IN",
		asnRegistry: "APNIC",
	},
	{
		source: "Certificate",
		ip: "103.85.78.6",
		range: "103.85.78.0 - 103.85.79.255",
		owner: "ADANI",
		country: "India",
		score: 950,
		asn: "AS136283",
		protocol: "HTTP",
		labels: ["Certificate", "Owned Range"],
		asnName: "ADANI-AS-IN",
		asnName2: "ADANI-AS-IN",
		asnRegistry: "APNIC",
	},
];

export const ipRanges = [
	{
		sources: ["Certificate", "DNS", "Owned Range"],
		rangeStart: "103.85.78.0",
		rangeEnd: "103.85.79.255",
		owner: "ADANI",
		autonomousSystem: "ADANI-AS-IN",
		autonomousSystemNumber: "AS136283",
		country: "India",
		ipCount: 9,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "210.212.128.40",
		rangeEnd: "210.212.128.47",
		owner: "NewsuryaNetwork",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 1,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "117.250.142.112",
		rangeEnd: "117.250.142.119",
		owner: "ADANI-PORTS-AND-SPECIAL-ECONOMIC-ZONE-LIMITED_BW-ID-1604",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 1,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "117.240.210.224",
		rangeEnd: "117.240.210.255",
		owner: "ADANI-GROUP-AHM",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 0,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "157.66.110.0",
		rangeEnd: "157.66.111.255",
		owner: "ACX2024",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 0,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "210.212.122.232",
		rangeEnd: "210.212.122.239",
		owner: "AllnnNetworkSHANTIGRAM",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 0,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "117.239.83.160",
		rangeEnd: "117.239.83.191",
		owner: "ADANIGROUP",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 0,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "117.239.35.224",
		rangeEnd: "117.239.35.255",
		owner: "ADANI-GROUP-AHM",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 0,
	},
	{
		sources: ["Owned Range"],
		rangeStart: "210.212.143.72",
		rangeEnd: "210.212.143.79",
		owner: "Custom-Network",
		autonomousSystem: "BSNL-NIB",
		autonomousSystemNumber: "AS9829",
		country: "India",
		ipCount: 0,
	},
];

export const documentTypes = [
	{ value: "breach-disclosure", label: "Breach or Incident Disclosure" },
	{ value: "iso-27001", label: "ISO 27001 Certificate" },
	{ value: "other-audit", label: "Other Audit Report" },
	{ value: "pen-test", label: "Penetration Test" },
	{ value: "questionnaire", label: "Questionnaire" },
	{ value: "soc1", label: "SOC1 Report" },
	{ value: "soc2", label: "SOC2 Report" },
	{ value: "soc3", label: "SOC3 Report" },
];

export const users = [
	{
		value: "albert-freeman",
		label: "Albert Freeman",
		role: "Primary Contact",
	},
	{ value: "devon-lane", label: "Devon Lane", role: "Legal" },
	{
		value: "darrell-steward",
		label: "Darrell Steward",
		role: "Security Officer",
	},
	{ value: "john-doe", label: "John Doe", role: "Technical Contact" },
];
